### ISSUE TITLE
Change package name to be pywinpty

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/pywinpty#18]
The module name is `winpty` but the package is named pywinpty.

We should have both names be the same, in this case I would lean towards `pywinpty`

@ccordoba12 what do you think?

**Comment by ccordoba12** [comment]
That's my take too, i.e. use `pywinpty`. This is also important to disambiguate the original library from its Python bindings, else things become a nightmare.

For example, we have `pip install graphviz` and `conda install graphviz`, which do different things (the first one installing the bindings and the second one the library).

**Comment by andfoy** [comment]
But as winpty is a C program, I don't see why we would have any module naming ambiguity problems. I think there would be problems if the package was called winpty.

**Comment by goanpeca** [comment]
@andfoy please change the python package to pywintpty both the name and folder (module name)

**Comment by andfoy** [comment]
Ok, I will do the changes. But I still think that is more intuitive to import winpty, as we're wrapping winpty library. For instance, at installation time we would execute:
```
pip install pywinpty
```
But to use it we would execute:
```python
import winpty
```

**Comment by ccordoba12** [comment]
It's the same with pyzmq:

    pip install pyzmq

```python
import zmq
```

so we have a good precedent here ;-)

**Comment by andfoy** [comment]
I agree with @ccordoba12, there are more packages that have different package and module names, such as OpenCV:
```
conda install opencv -c conda-forge
```

```
import cv2
```

**Comment by goanpeca** [comment]
@andfoy 

>I agree with @ccordoba12, there are more packages that have different package and module names, such as OpenCV:

>conda install opencv -c conda-forge
>import cv2

Is actually a bad example, cause there is no coherence on that naming.

**Comment by ccordoba12** [comment]
I'm sure `cv2` is the C library name. If so, it's the right thing to do :-)
